version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "fix(deps):"
      include: scope
    open-pull-requests-limit: 1
    